server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timeme_user
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

internal:
  secret: 65484e2cc795d3050f32f1065912d961ce8c8143f3e4442bc6593c46a5c02604